---
title: "Untitled"
author: "Emily Sheehan"
date: "31/10/2020"
output: html_document
---

```{r}
library(tidyverse)
library(leaflet)
library(patchwork)
```

```{r}
loc <- read_csv("data/locations.csv") %>% 
  select(c(site_id, description, latitude, longitude)) %>% 
  as_tibble()
readings <- read_csv("data/readings.csv")  %>% 
  as_tibble()
```

```{r}
unique(readings$units)
```

```{r}
sensors <- readings %>% 
  left_join(loc, by = "site_id") 
```

```{r}
sensors %>% 
  group_by(site_id, units) %>% 
  summarise(mean = mean(value, na.rm = TRUE),
            min = min(value, na.rm = TRUE),
            max = max(value, na.rm = TRUE),
            sd = sd(value, na.rm = TRUE)
            ) %>% 
  arrange(units) %>% 
  View()
```

```{r}
leaflet(loc) %>% 
  addProviderTiles("Esri") %>% 
  addMarkers(lng = loc$longitude,
             lat = loc$latitude,
             popup = loc$site_id)
```

```{r}
# density of wind speed
sensors %>% 
  filter(units == "km/h") %>% 
  ggplot(aes(value, group = site_id, fill = site_id )) +
  geom_density(alpha = 0.4) 
```
Are different parts of the city windier than others? How are the wind speed different or similar in different parts of
the city?

> month to month
> daily
> seasons
> time


```{r cache=TRUE}
sensors_wind <- sensors %>%
  mutate(month = lubridate::month(local_time)) %>%
  filter(units == "km/h") %>%
  mutate(time = format(as.POSIXct(local_time, "%Y-%m-%d %I:%M:%S %p"), format = "%H:%M")) %>%
  filter(!is.na(value))
           
          # strptime(as.POSIXct(local_time), "%I:%M %p"), format="%H:%M:%S"))
sensors_wind
```





```{r}
ggplot(sensors_wind,
       aes(x = month,
           y = value,
           group = month)) +
  geom_boxplot() +
  facet_wrap(~description)
```



```{r}
ggplot(sensors_wind,
       aes(x = month,
           y = value,
           group = description,
           color = description)) +
  geom_smooth() +
  geom_hline(aes(yintercept = mean(value))) +
  #facet_wrap(~description, 
   #          ncol = 2) +
  ylab("Wind Speed (km/hr)") +
  theme_bw()
```

```{r}
ggplot(sensors_wind,
       aes(x = site_id,
           y = value,
           group = description,
           color = description)) +
  geom_boxplot() +
  geom_hline(aes(yintercept = mean(value))) +
  #facet_wrap(~description, 
   #          ncol = 2) +
  xlab("") +
  ylab("Wind Speed (km/hr)") +
  theme_bw() +
  theme(axis.text.x = element_blank()) 

```
